repository: "hongyuanhua/hongyuanhua.github.io"
name: "Hongyuan Hua"
avatar: "assets/img/avatar.jpg"
position: "PhD Student @ University of Waterloo"
position2: "Research Scientist @ Visko Platform"
email: "hongyuan.hua@mail.utoronto.ca"
github: "hongyuanhua"
linkedin: "hongyuan-david-hua-659969110"
x: "huahongyuan"
location: "Toronto, ON"
research_interests:
  - Computer Vision
  - Generative Models
  - Video Generation & Editing
  - MLLMs

plugins:
  - jekyll-feed
